### ISSUE TITLE
Rewrite traffic_info using ChromeDriver

### ISSUE THREAD

**Issue by Da-Juan** [Da-Juan/traffic_info#1]
## Why?
webkit2png has not been maintained since a few years.

## ToDo

- [x] Continue to learn Python while rewriting traffic_info using `ChromeDriver`
- [x] Make a Python package
- [x] Write a documentation using `Sphinx`
- [x] Pass script arguments on command line or with a configuration file using `configargparse`
- [ ] Allow users to customize emails
- [x] Allow users to customize screenshot size
- [x] Auto-detect if ChromeDriver's binary is present in `PATH`
